modLoader="javafml"

loaderVersion="[35,)"

license="All rights reserved"

[[mods]]

modId="lifebinding"

version="1.16.4-1.0"

displayName="Life Binding"

authors="jayhill"

description='''
Adds potion of Life Binding. Inspired by LDShadowLady
'''