modLoader="javafml"

loaderVersion="[28,)"

displayURL="https://www.curseforge.com/minecraft/mc-mods/life-binding"

logoFile="life_binding.png"

[[mods]]

modId="lifebinding"

version="1.14.4-1.1"

displayName="Life Binding"

authors="jay"

credits="pau101, LDShadowLady"

description='''
Adds potion of Life Binding.
'''